# -*- coding: cp1252 -*-
import mysql.connector

def upload_mp3(cursor, file_path, title, artist):
    try:
        # Read the MP3 file
        with open(file_path, 'rb') as file:
            mp3_data = file.read()

        # Insert the MP3 file into the database
        query = "INSERT INTO Tracks (Track_Title, Artist_NAME, Track) VALUES (%s, %s, %s)"
        cursor.execute(query, (title, artist, mp3_data))

        print("MP3 uploaded successfully!")

    except Exception as e:
        print("Error: %s" % e)

try:
    conn = mysql.connector.connect(
        host='localhost',
        user='root',
        password='somyaa',
        database='music_playlist'
    )
    cursor = conn.cursor()

##    file_paths = [
##                    r"E:\MUSIC_NAPSTER0z\Alag Hai.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Baap Se.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Badan.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Bajenge.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Banjo.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Bas Mein.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Bhussi.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Blowing Up.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Boht Tej.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Cat Girls Are Ruining My Life!.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Cell Games.mp3",
##                    r"E:\MUSIC_NAPSTER0z\CG song.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Change Us.mp3",
##                    r"E:\MUSIC_NAPSTER0z\CODE MISTAKE.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Count Me Out.mp3",
##                    r"E:\MUSIC_NAPSTER0z\COWBELL WARRIOR!.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Creep (feat. Tom Ellis).mp3",
##                    r"E:\MUSIC_NAPSTER0z\Daaku.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Day 'N' Nite (From -Moon Knight-).mp3",
##                    r"E:\MUSIC_NAPSTER0z\DAYWALKER! (feat. CORPSE).mp3",
##                    r"E:\MUSIC_NAPSTER0z\Dhundhala.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Dil Ibaadat.mp3",
##                    r"E:\MUSIC_NAPSTER0z\DMs.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Dooba.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Drinks On Me.mp3",
##                    r"E:\MUSIC_NAPSTER0z\E-GIRLS ARE RUINING MY LIFE!.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Ek Do Ek.mp3",
##                    r"E:\MUSIC_NAPSTER0z\euphoria.mp3",
##                    r"E:\MUSIC_NAPSTER0z\FE!N (feat. Playboi Carti).mp3",
##                    r"E:\MUSIC_NAPSTER0z\Fire Again.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Forever.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Freeverse Feast.mp3",
##                    r"E:\MUSIC_NAPSTER0z\G.O.A.T..mp3",
##                    r"E:\MUSIC_NAPSTER0z\Galat Karam.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Galat Launda.mp3",
##                    r"E:\MUSIC_NAPSTER0z\GARAM.mp3",
##                    r"E:\MUSIC_NAPSTER0z\G-Yaan.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Happy Nation.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Heart Attack.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Heer Ranjha.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Heeriye.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Hoes Headquarters.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Hola Amigo.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Hola At Your Boy.mp3",
##                    r"E:\MUSIC_NAPSTER0z\HOT DEMON B!TCHES NEAR U ! ! !.mp3",
##                    r"E:\MUSIC_NAPSTER0z\I Guess.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Jhaag.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Judai.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Kaafizyada.mp3",
##                    r"E:\MUSIC_NAPSTER0z\KALESHI CHORI.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Kamikaze.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Keh Dena.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Khatta Flow.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Kheench Maari.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Kinaare.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Kya Mujhe Pyar Hai.mp3",
##                    r"E:\MUSIC_NAPSTER0z\KYA.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Lamhe.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Lavender.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Like That.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Luka Chippi.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Mary Jane.mp3",
##                    r"E:\MUSIC_NAPSTER0z\meet the grahams.mp3",
##                    r"E:\MUSIC_NAPSTER0z\MERA SAMAN KAHAN HAI-.mp3",
##                    r"E:\MUSIC_NAPSTER0z\MISA MISA!.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Miss YOU!.mp3",
##                    r"E:\MUSIC_NAPSTER0z\MORE.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Mrignaini.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Mrityu.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Mujhko Mila - Bonus Track.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Muse.mp3",
##                    r"E:\MUSIC_NAPSTER0z\N95.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Neurotica.mp3",
##                    r"E:\MUSIC_NAPSTER0z\No Cap.mp3",
##                    r"E:\MUSIC_NAPSTER0z\No Loss.mp3",
##                    r"E:\MUSIC_NAPSTER0z\No Surprises.mp3",
##                    r"E:\MUSIC_NAPSTER0z\NOAH.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Not Like Us.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Patterns.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Playing God.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Prarthana.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Redbone.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Roshni.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Run It (feat. Rick Ross & Rich Brian).mp3",
##                    r"E:\MUSIC_NAPSTER0z\Say My Name.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Secret.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Shake That.mp3",
##                    r"E:\MUSIC_NAPSTER0z\She Bad.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Smack That.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Submissive & Breedable.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Sunn Na.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Swimming Pools (Drank) - Extended Version.mp3",
##                    r"E:\MUSIC_NAPSTER0z\THAT’S A FACT!.mp3",
##                    r"E:\MUSIC_NAPSTER0z\The Last of Us 2 (Ellie's Song).mp3",
##                    r"E:\MUSIC_NAPSTER0z\The Real Slim Shady.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Thehra.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Tony Montana.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Tu Hi Meri Shab Hai.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Villain.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Where Is My Mind-.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Woh Raat.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Yezdi.mp3",
##                    r"E:\MUSIC_NAPSTER0z\Zubaida.mp3"]
##
##    titles = [
##        "Alag Hai",
##        "Baap Se",
##        "Badan",
##        "Bajenge",
##        "Banjo",
##        "Bas Mein",
##        "Bhussi",
##        "Blowing Up",
##        "Boht Tej",
##        "Cat Girls Are Ruining My Life!",
##        "Cell Games",
##        "Count Me Out",
##        "COWBELL WARRIOR!",
##        "Creep (feat. Tom Ellis)",
##        "Daaku",
##        "Day 'N' Nite (From -Moon Knight-)",
##        "DAYWALKER! (feat. CORPSE)",
##        "Dhundhala",
##        "Dil Ibaadat",
##        "DMs",
##        "Dooba",
##        "Drinks On Me",
##        "E-GIRLS ARE RUINING MY LIFE!",
##        "Ek Do Ek",
##        "euphoria",
##        "FE!N (feat. Playboi Carti)",
##        "Fire Again",
##        "Forever",
##        "Freeverse Feast",
##        "G.O.A.T.",
##        "Galat Karam",
##        "Galat Launda",
##        "GARAM",
##        "G-Yaan",
##        "Happy Nation",
##        "Heart Attack",
##        "Heer Ranjha",
##        "Heeriye",
##        "Hoes Headquarters",
##        "Hola Amigo",
##        "Hola At Your Boy",
##        "HOT DEMON B!TCHES NEAR U ! ! !",
##        "I Guess",
##        "Jhaag",
##        "Judai",
##        "Kaafizyada",
##        "KALESHI CHORI",
##        "Kamikaze",
##        "Keh Dena",
##        "Khatta Flow",
##        "Kheench Maari",
##        "Kinaare",
##        "Kya Mujhe Pyar Hai",
##        "KYA",
##        "Lamhe",
##        "Lavender",
##        "Like That",
##        "Luka Chippi",
##        "Mary Jane",
##        "meet the grahams",
##        "MERA SAMAN KAHAN HAI-",
##        "MISA MISA!",
##        "Miss YOU!",
##        "MORE",
##        "Mrignaini",
##        "Mrityu",
##        "Mujhko Mila - Bonus Track",
##        "Muse",
##        "N95",
##        "Neurotica",
##        "No Cap",
##        "No Loss",
##        "No Surprises",
##        "NOAH",
##        "Not Like Us",
##        "Patterns",
##        "Playing God",
##        "Prarthana",
##        "Redbone",
##        "Roshni",
##        "Run It (feat. Rick Ross & Rich Brian)",
##        "Say My Name",
##        "Secret",
##        "Shake That",
##        "She Bad",
##        "Smack That",
##        "Submissive & Breedable",
##        "Sunn Na",
##        "Swimming Pools (Drank) - Extended Version",
##        "THAT’S A FACT!",
##        "Through The Valley (Ellie's Song[Last of Us])",
##        "The Real Slim Shady",
##        "Thehra",
##        "Tony Montana",
##        "Tu Hi Meri Shab Hai",
##        "Villain",
##        "Where Is My Mind-",
##        "Woh Raat",
##        "Yezdi",
##        "Zubaida"]
##
##
##    
##    
##
##    artists = [
##        
##            "Badshah;Fotty Seven;Raga",
##            "Fotty Seven;KR$NA",
##            "Raga;Harjas Harjaayi",
##            "Badshah;Seedhe Maut",
##            "Fotty Seven",
##            "Bhuvan Bam",
##            "KSHMIR;Seedhe Maut;Karan Kanchan",
##            "KR$NA",
##            "Badshah;Fotty Seven",
##            "CORPSE",
##            "Sadzilla",
##            "KENDRICK LAMAR",
##            "SXMPRA",
##            "Tom Ellis(Lucifer Cast)",
##            "Badshah",
##            "Geek Music",
##            "mgk;CORPSE",
##            "Yashraj;Talwinder",
##            "KK",
##            "Nanku",
##            "Nanku",
##            "Badshah;MC STAN",
##            "CORPSE;Savage Ga$p",
##            "Tsumyoki;Rawal",
##            "KENDRICK LAMAR",
##            "Travis Scott;Playboi Carti",
##            "Ashnikko;VALORANT",
##            "Brodha V;KR$NA",
##            "KR$NA",
##            "Polyphia",
##            "Panther;Raga",
##            "Fotty Seven;MojoJojo",
##            "Chaar Diwaari;Rawal",
##            "Badshah",
##            "Ace of Base",
##            "Scarlxrd",
##            "Bhuvan Bam",
##            "Karun",
##            "Nanku",
##            "KR$NA;Seedhe Maut",
##            "Badshah;KR$NA;Prajina",
##            "CORPSE;Night Lovell",
##            "KR$NA",
##            "Chaar Diwaari",
##            "Kamran Ahmed",
##            "Nanku",
##            "DG IMMORTALS;Harjas Harjaayi;Raga",
##            "Nanku",
##            "Karun",
##            "Seedhe Maut;KR$NA",
##            "Raga;DG IMMORTALS",
##            "Karun",
##            "Kk",
##            "Chaar Diwari;Arpit Bala",
##            "Azzoz",
##            "Azzoz",
##            "Future;Metro Boomin;KENDRICK LAMAR",
##            "Seedhe Maut",
##            "Nanku",
##            "KENDRICK LAMAR",
##            "Chaar Diwaari",
##            "CORPSE;Scarlxrd;Kordhell",
##            "CORPSE",
##            "KDA;League of Legends",
##            "Karun;Nanku",
##            "Karun;Nanku;Multani",
##            "Karun;Adil;Chaar Diwaari",
##            "Karun;Adil",
##            "KENDRICK LAMAR",
##            "Polyphia",
##            "KR$NA",
##            "KR$NA",
##            "RADIOHEAD",
##            "Azzoz;Vedang",
##            "KENDRICK LAMAR",
##            "Azzoz;Devonian",
##            "Polyphia",
##            "KR$NA;Bharg",
##            "Childish Gambino",
##            "Chaar Diwaari",
##            "DJ Snake;Rick Ross;Rich Brain",
##            "KR$NA",
##            "Joshua Bassett",
##            "Eminem;Nate Dogg",
##            "Khantrast",
##            "Akon;Eminem",
##            "Smosh;bbno$",
##            "Bali",
##            "KENDICK LAMAR",
##            "Yashraj",
##            "Aashley Jhonson;Naughty Dogs[Last of Us]",
##            "Eminem",
##            "Chaar Diwaari",
##            "Karma;KR$NA",
##            "KK",
##            "KR$NA;Karma;Ikka",
##            "Pixies",
##            "Raftaar;KR$NA",
##            "Nanku",
##            "Nanku;Natiq"]
##
##    for file_path, title, artist in zip(file_paths, titles, artists):
##        upload_mp3(cursor, file_path, title, artist)
##
##    conn.commit()

finally:
    if 'cursor' in locals() and cursor is not None:
        cursor.close()
    if 'conn' in locals() and conn is not None:
        conn.close()
